ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.16.0-rc.0
    cli_version_sha: 17599d2f891ac41996936302b4f7b6d7e1359844
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    triggers:
      - src/**
    builds:
      - name: shared
        workflow: .github/workflows/build-shared.yaml
        triggers: []
    notify:
      repo: stablekernel/cascade-example-primary
      workflow: external-update.yaml
      token: CASCADE_STATE_TOKEN
      deploy_name: artifact-a
      environment: staging
  state:
    prerelease:
      sha: 6e80c086ec2c77b1afcb515e8fd19ec918b1c291
      version: v0.1.0-rc.1
      committed_at: "2026-07-14T07:14:11Z"
      committed_by: joshua-temple
