ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.2.0-rc.56
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    triggers:
      - src/**
    builds:
      - name: shared
        workflow: .github/workflows/build-shared.yaml
        triggers: []
    notify:
      repo: stablekernel/cascade-example-primary
      workflow: external-update.yaml
      token: CASCADE_STATE_TOKEN
  state:
    prerelease:
      sha: c1ffe1fcfc7b5bfaf06fe239aed6314a2ab6dac6
      version: v0.1.0-rc.11
      committed_at: "2026-06-18T01:23:47Z"
      committed_by: joshua-temple
