ci:
  config:
    schema_version: 1
    trunk_branch: main
    cli_version: v0.14.0-dryrun.50
    cli_version_sha: 31200d53c07ff9b0c3a3cf0032d671c686fe150c
    state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
    manifest_file: .github/manifest.yaml
    manifest_key: ci
    triggers:
      - src/**
    builds:
      - name: shared
        workflow: .github/workflows/build-shared.yaml
        triggers: []
    notify:
      repo: stablekernel/cascade-example-primary
      workflow: external-update.yaml
      token: CASCADE_STATE_TOKEN
      deploy_name: artifact-a
      environment: staging
  state:
    prerelease:
      sha: 689ba1a7359d4c2dcc5eaec5829d3216b431542c
      version: v0.14.0-dryrun.50
      committed_at: "2026-07-09T23:47:26Z"
      committed_by: joshua-temple
